# Generated by Django 5.2.16 on 2026-07-22 20:11

from django.db import migrations

DAYS = [
    (0, "Lunes"), (1, "Martes"), (2, "Miércoles"),
    (3, "Jueves"), (4, "Viernes"), (5, "Sábado"), (6, "Domingo"),
]


def seed_days(apps, schema_editor):
    DayOfWeek = apps.get_model("habits", "DayOfWeek")
    for number, name in DAYS:
        DayOfWeek.objects.get_or_create(number=number, defaults={"name": name})


def remove_days(apps, schema_editor):
    DayOfWeek = apps.get_model("habits", "DayOfWeek")
    DayOfWeek.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),  # confirma que este sea el nombre real de tu migración anterior
    ]
    operations = [
        migrations.RunPython(seed_days, reverse_code=remove_days),
    ]
